Timer
GangNamMango/LiarGame-backend pull request #20
Opened 2022-05-02 01:33 UTC by kjc6735

타이머를 만들었는데
어디서든 사용 가능하고, 쓰레드로 구현했습니다.
만약에 다른 컨트롤러에서 사용하려고 한다면 요청이 한번 더 필요할 것 같습니다.

2022-05-03 17:01 UTC, jjonyo requested changes
혹시 리뷰 이해 안되시는게 있으면 물어봐주시고 아님 전체회의전에 한번 구글미트로 같이 리팩토링 해봐도 좋을것같아요~!

2022-05-03 17:01 UTC, jjonyo commented on src/main/java/com/api/liargame/domain/GameTimer.java
> +        try {
`timer.scheduleAtFixedRate(task, delay, period);` 를 하면 알아서 period마다 task가 실행되는 걸로 아는데 이 try-catch문은 무슨 역할인가요?

2022-05-03 17:01 UTC, jjonyo commented on src/main/java/com/api/liargame/service/GameRoomServiceImpl.java
> +    Thread timerThread = new Thread(gameTimer);
스프링이 애초에 멀티스레드 환경에서 이 코드를 작동시키기때문에 굳이 스레드를 다시 생성해서 돌릴 필요는 없을 것 같아요.
그냥 GameTimer.run 코드를 실행시켜도 될것같습니다.

2022-05-03 17:01 UTC, jjonyo commented on src/main/java/com/api/liargame/service/GameRoomServiceImpl.java
> +    gameTimer.setGameRoom(gameRoom);
gameTimer도메인에 gameRoom을 통째로 넘기는거보다는, 타이머에 필요한 정보들만(roomId, time) 넘기는게 더 좋을것같습니다!

2022-05-03 17:01 UTC, jjonyo commented on src/main/java/com/api/liargame/domain/GameTimer.java
> +        private SimpMessagingTemplate webSocket;
Task내부에 웹소켓을 두면 setter가 두번 사용이 되어야하는데 그냥 GameTimer에 두고, Task에서 가져다 사용하는게 좋을 것 같습니다.

2022-05-03 17:01 UTC, jjonyo commented on src/main/java/com/api/liargame/domain/GameTimer.java
> +        private GameRoom gameRoom;
이런정보들도 두번 setter를 호출하지말고, Task를 생성할때 roomId와 time정보만 넘겨주어 사용하는게 좋을 것 같아요.

2022-05-05 06:58 UTC, kjc6735 commented on src/main/java/com/api/liargame/domain/GameTimer.java
> +        try {
timer.scheduleAtFixedRate(task, delay, period); 를 사용하면 시간은 정확하지만 clear하기 전까지 계속 실행되기 때문에, 시간만큼 기다린다음 끝내기 위해 사용했습니다.

2022-05-05 07:17 UTC, kjc6735 commented on src/main/java/com/api/liargame/service/GameRoomServiceImpl.java
> +    Thread timerThread = new Thread(gameTimer);
코드 중간에 사용하게 될 경우 Thread.sleep때문에 그 뒷코드가 sleep시간만큼 기다리는 시간이 있어서 일단은 쓰레드로 구현했습니다!
(계획에 저희가 시작하면 게임시작했습니다를 리턴하기로 되어있는데 저 코드가 리턴 전에 사용 되기 때문에 쓰레드가 필요하다구 생각했습니다..)

만약에 시작했습니다를 클라에 보내주고 클라에서 다시 pub/game/countdown 으로 요청을 보내서 따로 컨트롤러로 뺀다면 쓰레드로 구현 안해도 될 거 같습니다!

2022-05-05 09:07 UTC, jjonyo commented on src/main/java/com/api/liargame/domain/GameTimer.java
> +        try {
아하 그러면 Task의 `run()` 함수 내에서 time이 0이 되었을때 `timer.cancel()` 해주는건 어떤가요?

2022-05-05 09:07 UTC, jjonyo commented on src/main/java/com/api/liargame/service/GameRoomServiceImpl.java
> +    Thread timerThread = new Thread(gameTimer);
이건 delay를 좀 길게주고, 게임시작했습니다 를 리턴하기전에 미리 gameTimer를 실행시킨다음에 리턴하면 스레드로 돌것같긴한데 한번 테스트가 필요할것같네요

2022-05-07 11:35 UTC, jjonyo commented on src/main/java/com/api/liargame/constants/SettingConstant.java
> +  public final static Integer DEFAULT_TIME_LIMIT = 5;
테스트를 위해 바꾸신걸까요?

2022-05-07 11:38 UTC, jjonyo commented on src/main/java/com/api/liargame/service/GameRoomServiceImpl.java
> +          webSocket.convertAndSend("/sub/game/" + gameRoom.getRoomId() + "/countdown",
이거 응답값 내려주는부분 그때 노션에서 정했던것처럼 ResponseDto로 변경해주셔야할것같아요.
gameStatus부분은 아직 구현이 안됐으니 count만 담아주면 될것같아요!

2022-05-09 06:01 UTC, jjonyo approved these changes

2022-05-09 09:40 UTC, merged